---
- name: Development Environment
  hosts: all
  sudo: yes
  vars_files:
    - vars/main.yml  

  roles:
    - common
    - rvm
    - rails
    - { role: postgresql, when: install_postgresql }
    - { role: mysql, when: install_mysql }
    - redis
